# -*- coding: utf-8 -*-
"""task0.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/169eY4IrKI4mxCg6K_2Qx6FEk0NYMtGTk
"""

for i in range(1,101):
    if(i % 3 == 0):
        print("Fizz")
    elif(i % 5 == 0):
        print("Buzz")
    elif(i % 3 == 0 and i % 5 == 0 ):
        print("FizzBuzz")
    else:
        print(i)